import type { Metadata } from "next";
import "./globals.css";
import { jersey10 } from "@/font/fonts";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthProvider from "@/auth/providers/ NextAuthProvider";




export const metadata: Metadata = {
  title: "EduScape",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nextAuthSession = await getServerSession(authOptions);
  return (
    <html lang="en">
      <NextAuthProvider session={nextAuthSession}>

        <body className={`${jersey10.className} min-h-screen relative text-white`}>
          <div className="flex flex-col items-center justify-center min-h-screen">
            {children}
          </div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
