import type { Metadata } from "next";
import "./globals.css";
import { jersey10 } from "@/font/fonts";
import NextAuthProvider from "@/auth/providers/ NextAuthProvider";
import AudioPlayer from "@/component/AudioPlayer";




export const metadata: Metadata = {
  title: "EduScape",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en">
      <NextAuthProvider>

        <body className={`${jersey10.className} min-h-screen relative text-white`}>
          <div className="flex flex-col items-center justify-center min-h-screen">
            <AudioPlayer />
            {children}
          </div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
